{% set python_min = "3.10" %}
{% set name = "asf_tools" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a35f0234c5a8297e2b01f85db48324ee50add280423bf33f9494c2213f5edf42


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - make_composite = asf_tools.composite:main
    - water_map = asf_tools.hydrosar.water_map:main
    - calculate_hand = asf_tools.hydrosar.hand.calculate:main
    - flood_map = asf_tools.hydrosar.flood_map:main
    - generate_osm_dataset = asf_tools.watermasking.generate_osm_tiles:main
    - generate_worldcover_dataset = asf_tools.watermasking.generate_worldcover_tiles:main
    - fill_missing_tiles = asf_tools.watermasking.fill_missing_tiles:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - python-build
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }},<3.12
    - astropy-base
    - boto3
    - fiona
    - gdal >=3.7
    - geopandas
    - numpy
    - osmium-tool
    - pyogrio
    - pysheds >=0.3
    - rasterio
    - scikit-fuzzy
    - scikit-image
    - shapely
    - scipy
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - asf_tools
    - asf_tools.aws
    - asf_tools.composite
    - asf_tools.dem
    - asf_tools.raster
    - asf_tools.tile
    - asf_tools.util
    - asf_tools.vector
    - asf_tools.hydrosar.hand
    - asf_tools.hydrosar.threshold
    - asf_tools.hydrosar.water_map
    - asf_tools.hydrosar.flood_map
    - asf_tools.watermasking.generate_osm_tiles
    - asf_tools.watermasking.generate_worldcover_tiles
    - asf_tools.watermasking.fill_missing_tiles
  commands:
    - make_composite --help
    - water_map --help
    - calculate_hand --help
    - flood_map --help
    - generate_osm_dataset --help
    - generate_worldcover_dataset --help
    - fill_missing_tiles --help

about:
  home: https://github.com/ASFHyP3/asf-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools developed by ASF for working with SAR data

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jacquelynsmale
    - jtherrmann
    - forrestfwilliams
    - andrewplayer3
