{% set name = "asf_tools" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f21cb16d0a895ce3b357726373e74660bea5dd889f17965826f0366987a77e8f


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - make_composite = asf_tools.composite:main
    - water_map = asf_tools.hydrosar.water_map:main
    - calculate_hand = asf_tools.hydrosar.hand.calculate:main
    - flood_map = asf_tools.hydrosar.flood_map:main

requirements:
  host:
    - python >=3.8
    - pip
    - python-build
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - python >=3.8
    - astropy
    - boto3
    - fiona
    - gdal >=3.7
    - numpy
    - pysheds >=0.3
    - rasterio
    - scikit-fuzzy
    - scikit-image
    - shapely
    - scipy
    - tqdm

test:
  imports:
    - asf_tools
    - asf_tools.aws
    - asf_tools.composite
    - asf_tools.dem
    - asf_tools.raster
    - asf_tools.tile
    - asf_tools.util
    - asf_tools.vector
    - asf_tools.hydrosar.hand
    - asf_tools.hydrosar.threshold
    - asf_tools.hydrosar.water_map
    - asf_tools.hydrosar.flood_map
  commands:
    - make_composite --help
    - water_map --help
    - calculate_hand --help
    - flood_map --help

about:
  home: https://github.com/ASFHyP3/asf-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools developed by ASF for working with SAR data

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jacquelynsmale
    - jtherrmann
    - forrestfwilliams
